model_list:
  - model_name: MiniMax-M2.5
    litellm_params:
      model: openai/MiniMax-M2.5
      api_key: os.environ/SAMBANOVA_API_KEY
      api_base: https://api.sambanova.ai/v1
    model_info:
      input_cost_per_token: 0.0000003
      output_cost_per_token: 0.0000012
      tpm: 1000000
      rpm: 100

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
